package:
  name: error_tools
  # TODO: setup and use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  noarch: python
  script:
    - tree
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target error_tools
    - cmake --install . --prefix $PREFIX
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python {{ python }}
    - boost >=1.59
    - cmake >=3.17
    - eigen >=3.3.7
    - gcc_linux-64 =7.3.0
    - gxx_linux-64 =7.3.0
  host:
    - python
  run:
    - python >=3.8
    - boost
    - eigen >=3.3.7
    - gcc_linux-64 >=7.3.0
    - gxx_linux-64 >=7.3.0

test:
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_error_tools.cpp
  commands:
    - tree
    - mkdir build-package
    - cd build-package
    - cmake ..
    - cmake --build . --target test_error_tools
    - ctest -R test_error_tools
